In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.15.1


In [5]:
my_array = [12,13,1,8,9,66]
np_arr = np.array(my_array)
np_arr

array([12, 13,  1,  8,  9, 66])

In [6]:
print(np_arr)

[12 13  1  8  9 66]


In [7]:
my_tuple = (12,-3.5, 1 + 7j)
np_arr = np.array(my_tuple)
np_arr

array([12. +0.j, -3.5+0.j,  1. +7.j])

### Difference between python and numpy data structures

In [8]:
my_tuple * 6

(12,
 -3.5,
 (1+7j),
 12,
 -3.5,
 (1+7j),
 12,
 -3.5,
 (1+7j),
 12,
 -3.5,
 (1+7j),
 12,
 -3.5,
 (1+7j),
 12,
 -3.5,
 (1+7j))

In [9]:
np_arr * 6

array([ 72. +0.j, -21. +0.j,   6.+42.j])

### Intrinsic NumPy array creation using NumPy's methods

In [11]:
n_arr = np.arange(7)

In [12]:
n_arr

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
n_arr = np.arange(10,23)
n_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [21]:
n_arr.size

13

In [22]:
n_arr = np.arange(10,23, 5)  #start, stop and step
n_arr

array([10, 15, 20])

In [23]:
n_arr = np.arange(10,26, 5)
n_arr

array([10, 15, 20, 25])

### linspace(), zeros(), ones() and NumPy data types

In [24]:
n_arr = np.arange(26, step=5)  #start, stop and step, in this there is not start is given
n_arr

array([ 0,  5, 10, 15, 20, 25])

In [25]:
n_a = np.linspace(5, 15, 9)
n_a

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [26]:
n_a = np.linspace(5, 15, 9, retstep=True)
n_a

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
a = np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])
b = np.array([1,2,3])

c = a.dot(b)
c
              

array([14, 32, 50])

In [35]:
np.zeros((5,4,3))     #3 dimensional array, 4 and 3 tell's us matrix size, 5 tells us slabs

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
np.zeros(12,dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

### Slicing Array

In [40]:
my_vector = np.array([1,2,3,14,21,5,6,56,27,49])
my_vector

array([ 1,  2,  3, 14, 21,  5,  6, 56, 27, 49])

In [41]:
my_vector % 7

array([1, 2, 3, 0, 0, 5, 6, 0, 6, 0], dtype=int32)

In [43]:
my_vector.size

10

### Two Dimensional Array

In [47]:
my_array = np.arange(35)
my_array.shape=(7,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [48]:
my_array[2]

array([10, 11, 12, 13, 14])

In [49]:
my_array[-3]

array([20, 21, 22, 23, 24])

In [50]:
my_array[5,2]  # start from 0 index

27

In [51]:
row = 5
column = 2
my_array[row, column]

27

In [52]:
my_array[5][2]

27

### Three Dimensional Array

In [54]:
my_3d_array= np.arange(70)
my_3d_array.shape = (2, 7, 5)
my_3d_array


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [55]:
my_3d_array[1]


array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [56]:
my_3d_array[1,3]

array([50, 51, 52, 53, 54])

In [58]:
my_3d_array[1, 1, 2]

42

In [59]:
my_3d_array[1, 1, 2] = 108

In [60]:
my_3d_array

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34]],

       [[ 35,  36,  37,  38,  39],
        [ 40,  41, 108,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69]]])

### Boolean Mask arrays

In [65]:
my_v = np.array([-17, 0, 8, 7, 3,21])
my_v

array([-17,   0,   8,   7,   3,  21])

In [66]:
zero_mod_7_mask = 0 == (my_v % 7)
zero_mod_7_mask

array([False,  True, False,  True, False,  True])

In [70]:
my_v_sub = my_v[zero_mod_7_mask]
my_v_sub

array([ 0,  7, 21])

In [71]:
my_v_sub[my_v_sub > 0]

array([ 7, 21])

### Numpy Logical Operator

In [72]:
mod_test = 0 == (my_v % 7)

In [73]:
positive_test = my_v > 0

In [74]:
combined_mask = np.logical_and(mod_test, positive_test)

In [75]:
combined_mask

array([False, False, False,  True, False,  True])

In [77]:
my_v[combined_mask]

array([ 7, 21])

### Broadcasting

In [78]:
my_3d_a = np.arange(70)
my_3d_a.shape = (2, 7, 5)
my_3d_a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [81]:
#shape
my_3d_a.shape

(2, 7, 5)

In [80]:
# dimensions
my_3d_a.ndim

3

In [82]:
# matrix size
my_3d_a.size

70

In [83]:
# type of earch element
my_3d_a.dtype

dtype('int32')

In [84]:
5 * my_3d_a -2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [88]:
left_mat = np.arange(6).reshape(2,3)
right_mat = np.arange(15).reshape(3,5)

In [89]:
np.inner(left_mat,right_mat)

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [90]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

### Operations along axes

In [92]:
my_3d_a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [93]:
my_3d_a.shape

(2, 7, 5)

In [95]:
my_3d_a.sum()

2415

In [96]:
my_3d_a.sum(axis = 0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [97]:
my_3d_a.sum(axis = 1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [98]:
my_3d_a.sum(axis = 2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

### Broadcasting Rules

In [103]:
my_3d_array = np.ones(35, dtype='int').reshape(7,5) * 3

In [104]:
my_3d_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [116]:
my_3d_a = np.arange(70)
my_3d_a.shape = (2, 7, 5)
my_3d_a



array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [117]:
np_random_2d_a = np.random.random((7,5))


In [119]:
np.set_printoptions(precision = 4)
my_3d_a * np_random_2d_a

array([[[ 0.    ,  0.3272,  0.2459,  2.7048,  3.447 ],
        [ 4.1849,  2.4395,  2.4978,  2.2648,  0.7218],
        [ 9.9946,  1.1684,  5.6596,  5.5131,  1.413 ],
        [ 1.8423, 13.2425, 10.2419,  8.3905,  4.8401],
        [17.0121, 15.938 ,  3.6117, 10.1572,  5.5271],
        [23.8147,  6.4256, 11.0406, 16.7501,  6.1539],
        [24.2446, 24.4127, 27.117 , 17.2055,  6.2766]],

       [[34.0885, 11.7783,  4.5485, 34.2612, 33.6079],
        [33.4792, 16.6701, 14.9868, 12.1731,  3.5286],
        [44.9757,  4.8862, 22.1669, 20.3562,  4.9456],
        [ 6.1411, 42.2104, 31.3283, 24.7054, 13.7561],
        [46.7833, 42.5012,  9.3575, 25.6138, 13.5876],
        [57.1553, 15.0753, 25.3524, 37.6877, 13.581 ],
        [52.5299, 51.9755, 56.7763, 35.4537, 12.7379]]])

In [122]:
my_vector = np.arange(5) * 7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [123]:
my_3d_a/my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

### Creating Structured Arrays

In [191]:
person_data_def = [("name","50"),("height","f6"),("weight","72"),("age","50")]
person_data_def

[('name', '50'), ('height', 'f6'), ('weight', '72'), ('age', '50')]

In [192]:
people_array = np.zeros(4, dtype=person_data_def)

TypeError: data type "" not understood

In [193]:
person_record_a = np.rec.array([('Delta',71,22,33),('Alpha',99,75,12,33)], dtype=person_data_def)

TypeError: data type "" not understood